extends Node2D
# DUCKODUCKO — M1 prototype.
# Pixel-art sprites (art/, generated by tools/gen_sprites.py) blitted in _draw(),
# with a shape fallback. Menu -> drag to steer, tap to hop, fill LOFT for MEGA / LASER.

# ---- tunables ----------------------------------------------------------------
const VIEW := Vector2(540, 960)
const BASE_Y := 672.0
const DUCK_R := 30.0
const HOP_DUR := 0.52
const HOP_LIFT := 175.0
const MEGA_DUR := 2.6
const MEGA_LIFT := 540.0
const AIR_THRESHOLD := 0.15
const BASE_SPEED := 215.0       # px/s scroll
const SPEED_RAMP := 7.0         # px/s added per second survived (ramps quicker now)
const STEER_LERP := 14.0
const LOG_START_DIST := 160.0   # logs start soon after launch
const HERON_START := 900.0      # the heron shows up once you're warmed up

const LASER_DUR := 0.7
const LASER_W := 78.0

const WELL_DECK := ["well.", "rude.", "that's a log.", "ok.", "hm.", "a tragedy.", "splash.", "a HERON!"]

# collectibles: score (adds to distance) + loft fill + spawn weight
const ITEM_DEFS := [
	{"name": "feather", "score": 30.0, "loft": 0.12, "weight": 5},
	{"name": "bread",   "score": 20.0, "loft": 0.10, "weight": 3},
	{"name": "berry",   "score": 45.0, "loft": 0.16, "weight": 2},
	{"name": "bug",     "score": 70.0, "loft": 0.22, "weight": 1},
]

# duck-select screen
const MENU_DUCKS_BTN := Rect2(160.0, 770.0, 220.0, 56.0)
const SEL_BACK_BTN := Rect2(18.0, 28.0, 120.0, 52.0)
const SEL_PLAY_BTN := Rect2(160.0, 640.0, 220.0, 62.0)
const ROSTER := [
	{"name": "Mallard", "species": "mallard", "hop": 0.5, "steer": 0.5, "trait": "the balanced drake", "unlocked": true},
	{"name": "Hen Mallard", "species": "hen", "hop": 0.5, "steer": 0.55, "trait": "the clever hen", "unlocked": true},
	{"name": "Wood Duck", "species": "", "hop": 0.75, "steer": 0.5, "trait": "floaty show-off", "unlocked": false},
	{"name": "Bufflehead", "species": "", "hop": 0.6, "steer": 0.75, "trait": "tiny & twitchy", "unlocked": false},
	{"name": "Pintail", "species": "", "hop": 0.45, "steer": 0.85, "trait": "the best steerer", "unlocked": false},
]

# ---- state -------------------------------------------------------------------
enum St { GROUNDED, HOPPING, MEGA }
var in_menu := true
var in_select := false
var sel_index := 0
var select_yaw := 0.0
var spin_prev_x := 0.0
var species := "mallard"        # which roster duck is in play
var mega_style := "tumble"      # "tumble" or "fly" — picked per mega hop
var state := St.GROUNDED
var hop_t := 0.0
var mega_t := 0.0
var laser_t := 0.0

var duck_x := VIEW.x * 0.5
var target_x := VIEW.x * 0.5
var last_duck_x := VIEW.x * 0.5
var duck_vx := 0.0
var duck_shake := 0.0

var speed := BASE_SPEED
var distance := 0.0
var alive := true
var dead_msg := ""

var loft := 0.0
var loft_ready := false

var logs: Array = []           # {x, y, w, h, missed, phase, frog, frog_gone}
var items: Array = []          # {x, y, got, kind}
var enemies: Array = []        # {x, y, vy}  herons
var ripples: Array = []        # {x, y, t, max}
var wake: Array = []           # {x, y, t, side}

var log_timer := 0.0
var item_timer := 0.0
var heron_timer := 0.0
var wake_timer := 0.0
var idle_timer := 0.0

# ---- input bookkeeping -------------------------------------------------------
var pressed := false
var press_pos := Vector2.ZERO
var press_time := 0.0
var moved := false

# ---- nodes -------------------------------------------------------------------
var cam: Camera2D
var hud: CanvasLayer
var score_label: Label
var center_label: Label
var loft_bar
var font: Font

# ---- art ---------------------------------------------------------------------
const DUCK_DRAW := 2.0
var anim_t := 0.0
var ducks := {}                 # species -> {idle, turn, side, hop, face, stack}
var tex_shadow: Texture2D
var tex_log: Texture2D
var tex_frog: Texture2D
var tex_heron := []
var tex_items := {}
var tex_water: Texture2D
var has_art := false

func _ready() -> void:
	font = ThemeDB.fallback_font

	for sp in ["mallard", "hen"]:
		ducks[sp] = _load_duck(sp)
	tex_shadow = load("res://art/shadow.png")
	tex_log = load("res://art/log.png")
	tex_frog = load("res://art/frog.png")
	tex_heron = [load("res://art/heron_0.png"), load("res://art/heron_1.png")]
	tex_water = load("res://art/water.png")
	for kind in ITEM_DEFS:
		tex_items[kind.name] = load("res://art/%s.png" % kind.name)
	has_art = ducks.has("mallard") and ducks["mallard"]["idle"][0] != null and tex_water != null

	cam = Camera2D.new()
	cam.position = VIEW * 0.5
	cam.zoom = Vector2.ONE
	add_child(cam)
	cam.make_current()

	hud = CanvasLayer.new()
	add_child(hud)

	score_label = Label.new()
	score_label.position = Vector2(20, 18)
	score_label.add_theme_font_size_override("font_size", 34)
	hud.add_child(score_label)

	center_label = Label.new()
	center_label.size = Vector2(VIEW.x, 200)
	center_label.position = Vector2(0, VIEW.y * 0.34)
	center_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	center_label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	center_label.add_theme_font_size_override("font_size", 44)
	center_label.visible = false
	hud.add_child(center_label)

	loft_bar = (load("res://LoftBar.gd")).new()
	loft_bar.size = Vector2(360, 54)
	loft_bar.position = Vector2(VIEW.x * 0.5 - 180, VIEW.y - 96)
	hud.add_child(loft_bar)

	reset_game()
	_enter_menu()

func _load_duck(sp: String) -> Dictionary:
	var d := {}
	d["idle"] = [load("res://art/%s_idle_0.png" % sp), load("res://art/%s_idle_1.png" % sp)]
	d["turn"] = {-1: load("res://art/%s_turn_left.png" % sp), 1: load("res://art/%s_turn_right.png" % sp)}
	d["bank"] = []                                    # 0=hard left .. 3=straight .. 6=hard right
	for bi in range(7):
		var bp := "res://art/%s_bank_%d.png" % [sp, bi]
		d["bank"].append(load(bp) if ResourceLoader.exists(bp) else null)
	d["side"] = {-1: load("res://art/%s_side_left.png" % sp), 1: load("res://art/%s_side_right.png" % sp)}
	d["hop"] = [load("res://art/%s_hop_0.png" % sp), load("res://art/%s_hop_1.png" % sp)]
	d["face"] = load("res://art/%s_face.png" % sp)
	var hp := "res://art/%s_hero.png" % sp                 # front 3/4 for menu (gameplay is back view)
	d["hero"] = load(hp) if ResourceLoader.exists(hp) else null
	var st := []
	for zi in range(64):
		var p := "res://art/%s_stack_%02d.png" % [sp, zi]
		if not ResourceLoader.exists(p):
			break
		st.append(load(p))
	d["stack"] = st
	return d

func _dbg() -> void:
	await get_tree().create_timer(0.3).timeout
	await RenderingServer.frame_post_draw
	get_viewport().get_texture().get_image().save_png("/tmp/s_menu.png")
	_open_select()
	sel_index = 1                       # the Hen
	await get_tree().create_timer(0.5).timeout
	await RenderingServer.frame_post_draw
	get_viewport().get_texture().get_image().save_png("/tmp/s_select.png")
	start_game()                        # species becomes hen
	distance = 1300.0
	logs.append({"x": 130.0, "y": 200.0, "w": 170.0, "h": 46.0, "missed": false, "phase": 0.0, "frog": true, "frog_gone": false})
	enemies.append({"x": 300.0, "y": 360.0, "vy": 0.0})
	state = St.HOPPING
	hop_t = HOP_DUR * 0.4
	await get_tree().create_timer(0.05).timeout
	await RenderingServer.frame_post_draw
	get_viewport().get_texture().get_image().save_png("/tmp/s_play.png")
	state = St.GROUNDED
	loft = 1.0
	loft_ready = true
	mega_hop()
	mega_style = "tumble"
	mega_t = MEGA_DUR * 0.4
	await get_tree().create_timer(0.05).timeout
	await RenderingServer.frame_post_draw
	get_viewport().get_texture().get_image().save_png("/tmp/s_mega.png")
	get_tree().quit()

func _enter_menu() -> void:
	in_menu = true
	in_select = false
	score_label.visible = false
	loft_bar.visible = false
	center_label.visible = false
	cam.zoom = Vector2.ONE
	cam.offset = Vector2.ZERO

func _open_select() -> void:
	in_menu = false
	in_select = true
	select_yaw = 0.0

func start_game() -> void:
	in_menu = false
	in_select = false
	var sp: String = ROSTER[sel_index].species
	if sp != "":
		species = sp
	reset_game()
	score_label.visible = true
	loft_bar.visible = true

func reset_game() -> void:
	state = St.GROUNDED
	hop_t = 0.0
	mega_t = 0.0
	laser_t = 0.0
	duck_x = VIEW.x * 0.5
	target_x = duck_x
	last_duck_x = duck_x
	duck_vx = 0.0
	duck_shake = 0.0
	speed = BASE_SPEED
	distance = 0.0
	alive = true
	dead_msg = ""
	loft = 0.0
	loft_ready = false
	logs.clear()
	items.clear()
	enemies.clear()
	ripples.clear()
	wake.clear()
	log_timer = 0.8
	item_timer = 0.4
	heron_timer = 6.0
	wake_timer = 0.0
	idle_timer = 0.0
	cam.zoom = Vector2.ONE
	cam.offset = Vector2.ZERO
	center_label.visible = false

# ---- input -------------------------------------------------------------------
func _input(event: InputEvent) -> void:
	if event is InputEventScreenTouch or event is InputEventMouseButton:
		if event.pressed:
			_on_press(event.position)
		else:
			_on_release()
	elif event is InputEventScreenDrag:
		_on_drag(event.position)
	elif event is InputEventMouseMotion and (event.button_mask & MOUSE_BUTTON_MASK_LEFT):
		_on_drag(event.position)
	elif event is InputEventKey and event.pressed and not event.echo:
		if event.keycode == KEY_SPACE:
			if in_menu: start_game()
			else: hop()
		elif event.keycode == KEY_M:
			mega_hop()
		elif event.keycode == KEY_L:
			fire_laser()

func _on_press(pos: Vector2) -> void:
	idle_timer = 0.0
	if in_menu:
		if MENU_DUCKS_BTN.has_point(pos):
			_open_select()
		else:
			start_game()
		return
	if in_select:
		_select_press(pos)
		return
	if not alive:
		reset_game()
		return
	# tapping the (ready) LOFT bar: left half = MEGA, right half = LASER
	if loft_ready and Rect2(loft_bar.position, loft_bar.size).has_point(pos):
		if pos.x < loft_bar.position.x + loft_bar.size.x * 0.5:
			mega_hop()
		else:
			fire_laser()
		return
	pressed = true
	moved = false
	press_pos = pos
	press_time = Time.get_ticks_msec() / 1000.0

func _on_drag(pos: Vector2) -> void:
	if in_select:
		select_yaw += (pos.x - spin_prev_x) * 0.012
		spin_prev_x = pos.x
		return
	if in_menu or not alive:
		return
	if (pos - press_pos).length() > 18.0:
		moved = true
	target_x = clampf(pos.x, DUCK_R, VIEW.x - DUCK_R)

func _select_press(pos: Vector2) -> void:
	spin_prev_x = pos.x
	if SEL_BACK_BTN.has_point(pos):
		_enter_menu()
		return
	if SEL_PLAY_BTN.has_point(pos) and ROSTER[sel_index].unlocked:
		start_game()
		return
	for i in ROSTER.size():
		if _thumb_rect(i).has_point(pos) and ROSTER[i].unlocked:
			sel_index = i
			return

func _on_release() -> void:
	if not pressed:
		return
	pressed = false
	var dur := Time.get_ticks_msec() / 1000.0 - press_time
	if not moved and dur < 0.30:
		hop()

# ---- actions -----------------------------------------------------------------
func hop() -> void:
	idle_timer = 0.0
	if not alive or in_menu:
		return
	if state == St.GROUNDED:
		state = St.HOPPING
		hop_t = 0.0

func mega_hop() -> void:
	if not alive or in_menu or not loft_ready or state == St.MEGA or laser_t > 0.0:
		return
	state = St.MEGA
	mega_t = 0.0
	mega_style = "fly" if randf() < 0.5 else "tumble"
	loft = 0.0
	loft_ready = false

func fire_laser() -> void:
	if not alive or in_menu or not loft_ready or state == St.MEGA:
		return
	laser_t = LASER_DUR
	loft = 0.0
	loft_ready = false

func die(msg: String) -> void:
	alive = false
	dead_msg = msg
	center_label.text = msg + "\n\ntap to retry"
	center_label.visible = true

# ---- per-frame ---------------------------------------------------------------
func _process(delta: float) -> void:
	anim_t += delta
	if in_select:
		select_yaw += delta * 0.7
	if not in_menu and not in_select and alive:
		_update_play(delta)
	_update_ripples(delta)
	queue_redraw()

func _update_play(delta: float) -> void:
	speed = BASE_SPEED + SPEED_RAMP * (distance / 200.0)
	distance += speed * delta
	idle_timer += delta

	duck_x = lerpf(duck_x, target_x, clampf(delta * STEER_LERP, 0.0, 1.0))
	duck_vx = (duck_x - last_duck_x) / maxf(delta, 0.0001)
	last_duck_x = duck_x
	if duck_shake > 0.0:
		duck_shake = maxf(0.0, duck_shake - delta)

	_update_hop(delta)
	_update_wake(delta)
	_update_enemies(delta)
	_spawn(delta)
	_move_world(delta)
	if laser_t > 0.0:
		laser_t -= delta
		_laser_burn()
		cam.offset = Vector2(randf_range(-1, 1), randf_range(-1, 1)) * 7.0
	else:
		cam.offset = Vector2.ZERO
	_collide()
	_refresh_hud()

func _update_hop(delta: float) -> void:
	match state:
		St.HOPPING:
			hop_t += delta
			if hop_t / HOP_DUR >= 1.0:
				state = St.GROUNDED
				_land(false)
		St.MEGA:
			mega_t += delta
			var z := 1.0 - 0.26 * hop_height()
			cam.zoom = Vector2(z, z)
			for it in items:
				if not it.got and absf(it.x - duck_x) < 70.0:
					_collect(it)
			if mega_t / MEGA_DUR >= 1.0:
				state = St.GROUNDED
				cam.zoom = Vector2.ONE
				_land(true)

func hop_height() -> float:
	match state:
		St.HOPPING:
			return sin((hop_t / HOP_DUR) * PI)
		St.MEGA:
			return sin((mega_t / MEGA_DUR) * PI)
		_:
			return 0.0

func is_airborne() -> bool:
	return state == St.MEGA or (state == St.HOPPING and hop_height() > AIR_THRESHOLD)

func is_invincible() -> bool:
	return state == St.MEGA or laser_t > 0.0

func _land(mega: bool) -> void:
	ripples.append({"x": duck_x, "y": BASE_Y, "t": 0.0, "max": 220.0 if mega else 90.0})
	if mega:
		_flash("WHEE.")

func _update_wake(delta: float) -> void:
	wake_timer -= delta
	if wake_timer <= 0.0 and state != St.MEGA:
		wake.append({"x": duck_x, "y": BASE_Y + 10.0, "t": 0.0, "side": -1.0})
		wake.append({"x": duck_x, "y": BASE_Y + 10.0, "t": 0.0, "side": 1.0})
		wake_timer = 0.045
	for p in wake:
		p.t += delta
		p.y += speed * delta * 0.9
	wake = wake.filter(func(p): return p.t < 1.1)

func _update_enemies(delta: float) -> void:
	for e in enemies:
		e.y += e.vy * delta
	enemies = enemies.filter(func(e): return e.y < VIEW.y + 100.0)

func _spawn(delta: float) -> void:
	log_timer -= delta
	if log_timer <= 0.0 and distance > LOG_START_DIST:
		var w := randf_range(110.0, 230.0)
		logs.append({
			"x": randf_range(w * 0.5, VIEW.x - w * 0.5),
			"y": -60.0, "w": w, "h": 46.0, "missed": false,
			"phase": randf() * TAU, "frog": randf() < 0.35, "frog_gone": false,
		})
		log_timer = randf_range(0.65, 1.15) * (BASE_SPEED / speed) + 0.25

	item_timer -= delta
	if item_timer <= 0.0:
		items.append({"x": randf_range(40.0, VIEW.x - 40.0), "y": -40.0, "got": false, "kind": _pick_kind()})
		item_timer = randf_range(0.55, 1.2)

	heron_timer -= delta
	if heron_timer <= 0.0 and distance > HERON_START:
		var hx := clampf(duck_x + randf_range(-140.0, 140.0), 40.0, VIEW.x - 40.0)
		enemies.append({"x": hx, "y": -80.0, "vy": speed + 320.0})
		heron_timer = randf_range(4.5, 8.0)

func _pick_kind() -> int:
	var total := 0
	for k in ITEM_DEFS:
		total += k.weight
	var r := randi() % total
	for i in ITEM_DEFS.size():
		r -= ITEM_DEFS[i].weight
		if r < 0:
			return i
	return 0

func _move_world(delta: float) -> void:
	var dy := speed * delta
	for l in logs:
		l.y += dy
	for it in items:
		it.y += dy
	logs = logs.filter(func(l): return l.y < VIEW.y + 80.0)
	items = items.filter(func(it): return it.y < VIEW.y + 60.0 and not it.got)

func _laser_burn() -> void:
	# obliterate everything in the duck's column above it
	var survivors: Array = []
	for l in logs:
		if l.y < BASE_Y + 24.0 and absf(l.x - duck_x) < LASER_W * 0.5 + l.w * 0.5:
			ripples.append({"x": l.x, "y": l.y, "t": 0.0, "max": 70.0})
		else:
			survivors.append(l)
	logs = survivors
	var e_survivors: Array = []
	for e in enemies:
		if absf(e.x - duck_x) < LASER_W * 0.5 + 30.0:
			ripples.append({"x": e.x, "y": e.y, "t": 0.0, "max": 80.0})
		else:
			e_survivors.append(e)
	enemies = e_survivors

func _collide() -> void:
	for it in items:
		if not it.got and Vector2(it.x - duck_x, it.y - BASE_Y).length() < DUCK_R + 18.0:
			_collect(it)

	for l in logs:
		if absf(l.x - duck_x) < l.w * 0.5 + DUCK_R * 0.52 and absf(l.y - BASE_Y) < l.h * 0.5 + DUCK_R * 0.52:
			if is_airborne() or is_invincible():
				if not l.missed:
					l.missed = true
					duck_shake = 0.18
					_add_loft(0.10)
					if l.frog and not l.frog_gone:
						l.frog_gone = true
						ripples.append({"x": l.x - l.w * 0.3, "y": l.y, "t": 0.0, "max": 50.0})
			else:
				die(WELL_DECK[randi() % WELL_DECK.size()])
				return

	# the heron dive ignores hopping (it's aerial) — you must STEER clear, or be invincible
	if not is_invincible():
		for e in enemies:
			if absf(e.x - duck_x) < 44.0 and absf(e.y - BASE_Y) < 42.0:
				die("a HERON!")
				return

func _collect(it: Dictionary) -> void:
	it.got = true
	var def: Dictionary = ITEM_DEFS[it.kind]
	distance += def.score * 0.6
	_add_loft(def.loft)
	ripples.append({"x": it.x, "y": it.y, "t": 0.0, "max": 40.0})

func _add_loft(amount: float) -> void:
	loft = clampf(loft + amount, 0.0, 1.0)
	if loft >= 1.0:
		loft_ready = true

func _update_ripples(delta: float) -> void:
	for r in ripples:
		r.t += delta
	ripples = ripples.filter(func(r): return r.t < 0.6)

func _flash(msg: String) -> void:
	center_label.text = msg
	center_label.visible = true
	await get_tree().create_timer(0.7).timeout
	if alive and not in_menu:
		center_label.visible = false

func _refresh_hud() -> void:
	score_label.text = "%d m" % int(distance / 10.0)
	loft_bar.value = loft
	loft_bar.is_ready = loft_ready

# ---- drawing -----------------------------------------------------------------
func _draw() -> void:
	var scroll: float = anim_t * 80.0 if in_menu else distance

	# water (tiled, scrolling) or flat-color fallback
	if has_art:
		var t := tex_water.get_size()
		var off := fmod(scroll, t.y)
		var y := -t.y + off
		while y < VIEW.y:
			var x := 0.0
			while x < VIEW.x:
				draw_texture(tex_water, Vector2(x, y))
				x += t.x
			y += t.y
	else:
		draw_rect(Rect2(Vector2.ZERO, VIEW), Color(0.30, 0.62, 0.78))

	if in_menu:
		_draw_menu()
		return

	if in_select:
		_draw_select()
		return

	# water trail / wake
	for p in wake:
		var a: float = 1.0 - p.t / 1.1
		draw_circle(Vector2(p.x + p.side * p.t * 26.0, p.y), 2.0 + p.t * 6.0, Color(1, 1, 1, 0.22 * a))

	# landing ripples
	for r in ripples:
		var rp: float = r.t / 0.6
		draw_arc(Vector2(r.x, r.y), r.max * rp, 0, TAU, 28, Color(1, 1, 1, 0.5 * (1.0 - rp)), 3.0)

	# logs (bob + sway) with frog passenger
	for l in logs:
		var bob: float = sin(anim_t * 2.0 + l.phase) * 3.0
		var sway: float = sin(anim_t * 1.3 + l.phase) * 0.05
		draw_set_transform(Vector2(l.x, l.y + bob), sway, Vector2.ONE)
		if has_art:
			draw_texture_rect(tex_log, Rect2(-l.w * 0.5, -l.h * 0.5, l.w, l.h), false)
			if l.frog and not l.frog_gone:
				var fz := tex_frog.get_size() * 2.0
				var fhop: float = absf(sin(anim_t * 3.0 + l.phase)) * 4.0
				draw_texture_rect(tex_frog, Rect2(Vector2(-l.w * 0.28, -fhop) - fz * 0.5, fz), false)
		else:
			draw_rect(Rect2(-l.w * 0.5, -l.h * 0.5, l.w, l.h), Color(0.45, 0.30, 0.18))
	draw_set_transform(Vector2.ZERO, 0.0, Vector2.ONE)

	# collectibles
	for it in items:
		if it.got:
			continue
		if has_art:
			var tex: Texture2D = tex_items[ITEM_DEFS[it.kind].name]
			var isz := tex.get_size() * 2.0
			draw_texture_rect(tex, Rect2(Vector2(it.x, it.y + sin(anim_t * 4.0 + it.x) * 2.0) - isz * 0.5, isz), false)
		else:
			_draw_diamond(Vector2(it.x, it.y), 12.0, Color(1.0, 0.92, 0.45))

	# heron telegraph shadow + heron
	for e in enemies:
		if e.y < BASE_Y and has_art:
			var prox: float = clampf(1.0 - (BASE_Y - e.y) / 520.0, 0.08, 1.0)
			var hs := tex_shadow.get_size() * DUCK_DRAW * (0.6 + prox)
			draw_texture_rect(tex_shadow, Rect2(Vector2(e.x, BASE_Y) - hs * 0.5, hs), false, Color(1, 1, 1, prox))
	for e in enemies:
		var hf: Texture2D = tex_heron[int(anim_t * 11.0) % 2] if has_art else null
		if hf != null:
			var ez: Vector2 = hf.get_size() * DUCK_DRAW
			draw_texture_rect(hf, Rect2(Vector2(e.x, e.y) - ez * 0.5, ez), false)
		else:
			draw_circle(Vector2(e.x, e.y), 34.0, Color(0.5, 0.55, 0.62))

	# laser beam (under the duck)
	if laser_t > 0.0:
		var flick: float = 0.7 + 0.3 * sin(anim_t * 60.0)
		draw_rect(Rect2(duck_x - LASER_W * 0.7, 0, LASER_W * 1.4, BASE_Y), Color(1, 0.3, 0.3, 0.14 * flick))
		draw_rect(Rect2(duck_x - LASER_W * 0.5, 0, LASER_W, BASE_Y), Color(1, 0.5, 0.4, 0.42 * flick))
		draw_rect(Rect2(duck_x - LASER_W * 0.18, 0, LASER_W * 0.36, BASE_Y), Color(1, 1, 1, 0.85 * flick))

	_draw_duck()

	if alive and state == St.GROUNDED and idle_timer > 4.0:
		var dp := Vector2(duck_x, BASE_Y)
		draw_string(font, dp + Vector2(-26, -DUCK_R - 40), "quack?",
			HORIZONTAL_ALIGNMENT_LEFT, -1, 26, Color(1, 1, 1, 0.9))

func _draw_duck() -> void:
	var h := hop_height()
	var shake_x := (randf() - 0.5) * 14.0 if duck_shake > 0.0 else 0.0
	var lift: float = HOP_LIFT if state != St.MEGA else MEGA_LIFT
	var duck_pos := Vector2(duck_x + shake_x, BASE_Y - h * lift)
	var duck_scale := 1.0 + (0.35 if state != St.MEGA else 1.2) * h

	if has_art:
		var ss := tex_shadow.get_size() * DUCK_DRAW
		var swf := 1.0 - 0.55 * h
		var sw := Vector2(ss.x * swf, ss.y * swf)
		draw_texture_rect(tex_shadow, Rect2(Vector2(duck_x, BASE_Y + 8) - sw * 0.5, sw),
			false, Color(1, 1, 1, 1.0 - 0.4 * h))
		var st_slices = ducks[species]["stack"]
		if state == St.MEGA and not st_slices.is_empty():
			# MEGA HOP: the duck becomes the 3D voxel — tumbling or flying
			var p := mega_t / MEGA_DUR
			var yaw: float = p * TAU * 0.5 if mega_style == "fly" else p * TAU * 2.0
			var roll: float = sin(p * PI) * 0.22 if mega_style == "fly" else p * TAU
			_draw_stack(duck_pos, 2.4 + 1.8 * h, st_slices, yaw, roll, false)
		else:
			var fr := _duck_frame(h)
			var ds := fr.get_size() * DUCK_DRAW * duck_scale
			draw_texture_rect(fr, Rect2(duck_pos - ds * 0.5, ds), false)
	else:
		draw_circle(Vector2(duck_x, BASE_Y + 6), DUCK_R * (1.0 - 0.55 * h), Color(0, 0, 0, 0.22 * (1.0 - 0.4 * h)))
		draw_circle(duck_pos, DUCK_R * duck_scale, Color(0.97, 0.84, 0.27))

func _duck_frame(h: float) -> Texture2D:
	var cur = ducks[species]
	var f = _pick_duck_tex(h, cur)
	if f == null:                                  # asset missing -> safe fallback
		f = cur["idle"][int(anim_t * 3.0) % 2]
	return f

func _pick_duck_tex(h: float, cur):
	if h > 0.06:                                   # airborne -> wings out, flapping
		return cur["hop"][int(anim_t * 18.0) % 2]
	if duck_vx < -205.0:
		return cur["side"][-1]
	if duck_vx > 205.0:
		return cur["side"][1]
	var bank: Array = cur.get("bank", [])             # smooth banking across steering range
	if not bank.is_empty():
		var t := clampf((duck_vx + 205.0) / 410.0, 0.0, 1.0)   # 0 (left) .. 1 (right)
		var idx := int(round(t * float(bank.size() - 1)))
		if bank[idx] != null:
			return bank[idx]
	if duck_vx < -45.0:                               # fallback: discrete poses
		return cur["turn"][-1]
	if duck_vx > 45.0:
		return cur["turn"][1]
	return cur["idle"][int(anim_t * 3.0) % 2]

# ---- menu --------------------------------------------------------------------
func _draw_menu() -> void:
	var cx := VIEW.x * 0.5
	# title
	var tbob := sin(anim_t * 2.0) * 6.0
	draw_string(font, Vector2(0, 200 + tbob), "DUCKODUCKO", HORIZONTAL_ALIGNMENT_CENTER, VIEW.x, 66, Color(1, 0.92, 0.45))
	draw_string(font, Vector2(0, 246 + tbob), "a whimsical duck hopper", HORIZONTAL_ALIGNMENT_CENTER, VIEW.x, 24, Color(0.95, 0.97, 1.0, 0.85))

	if has_art:
		# orbiting collectibles around the centered hero
		var orbit := [["feather", 0.0], ["berry", 2.1], ["bug", 4.2]]
		for o in orbit:
			var ang: float = anim_t * 0.8 + float(o[1])
			var pos := Vector2(cx + cos(ang) * 200.0, 450.0 + sin(ang) * 80.0)
			var otex = tex_items[o[0]]
			_blit_centered(otex, pos, 1.8)
		# the star: drake centered; hen a smaller companion to the side (front-facing hero shots)
		var hen_hero = ducks["hen"].get("hero")
		var drake_hero = ducks["mallard"].get("hero")
		_blit_centered(hen_hero if hen_hero != null else ducks["hen"]["idle"][0], Vector2(cx + 150, 482.0 + sin(anim_t * 2.5 + 0.6) * 9.0), 2.8)
		_blit_centered(drake_hero if drake_hero != null else ducks["mallard"]["idle"][0], Vector2(cx, 448.0 + sin(anim_t * 2.5) * 10.0), 4.6)

	# tap-to-play, pulsing
	var pulse := 0.55 + 0.45 * sin(anim_t * 4.0)
	draw_string(font, Vector2(0, 700), "▶  tap to play  ◀", HORIZONTAL_ALIGNMENT_CENTER, VIEW.x, 36, Color(1, 1, 1, pulse))
	# DUCKS button (opens the select screen)
	draw_style_box(_btn_sb(), MENU_DUCKS_BTN)
	draw_string(font, Vector2(MENU_DUCKS_BTN.position.x, MENU_DUCKS_BTN.position.y + 33), "🦆  DUCKS  ▸",
		HORIZONTAL_ALIGNMENT_CENTER, MENU_DUCKS_BTN.size.x, 24, Color(1, 1, 1, 0.95))
	draw_string(font, Vector2(0, 900), "drag to steer · tap to hop · fill LOFT for MEGA HOP / LASER",
		HORIZONTAL_ALIGNMENT_CENTER, VIEW.x, 18, Color(1, 1, 1, 0.6))

func _btn_sb() -> StyleBoxFlat:
	var s := StyleBoxFlat.new()
	s.bg_color = Color(0.10, 0.20, 0.30, 0.9)
	s.set_corner_radius_all(14)
	s.set_border_width_all(2)
	s.border_color = Color(1, 1, 1, 0.4)
	return s

func _blit_centered(tex, pos: Vector2, scale: float) -> void:
	if tex == null:
		return
	var sz: Vector2 = tex.get_size() * scale
	draw_texture_rect(tex, Rect2(pos - sz * 0.5, sz), false)

# ---- duck-select screen ------------------------------------------------------
func _thumb_rect(i: int) -> Rect2:
	var n := ROSTER.size()
	var tw := 86.0
	var x0 := VIEW.x * 0.5 - n * tw * 0.5
	return Rect2(x0 + i * tw + 6.0, 770.0, tw - 12.0, 86.0)

func _draw_select() -> void:
	var cx := VIEW.x * 0.5
	draw_string(font, Vector2(0, 110), "CHOOSE YOUR DUCK", HORIZONTAL_ALIGNMENT_CENTER, VIEW.x, 40, Color(1, 0.92, 0.45))

	draw_style_box(_btn_sb(), SEL_BACK_BTN)
	draw_string(font, Vector2(SEL_BACK_BTN.position.x, SEL_BACK_BTN.position.y + 33), "< back",
		HORIZONTAL_ALIGNMENT_CENTER, SEL_BACK_BTN.size.x, 22, Color.WHITE)

	var duck = ROSTER[sel_index]
	var unlocked: bool = duck.unlocked
	var sp: String = duck.species
	var bob := sin(anim_t * 2.5) * 8.0
	# big PIXEL-ART render that cycles through poses (a little turntable)
	if unlocked and sp != "" and ducks.has(sp):
		var poses = _showcase(ducks[sp])
		var fr = poses[int(anim_t * 1.6) % poses.size()]
		_blit_centered(fr, Vector2(cx, 320.0 + bob), 6.0)
	else:
		var lhero = ducks["mallard"].get("hero")
		_blit_modulated(lhero if lhero != null else ducks["mallard"]["idle"][0], Vector2(cx, 320.0 + bob), 6.0, Color(0.32, 0.35, 0.42, 1.0))
		draw_string(font, Vector2(0, 355.0), "LOCKED", HORIZONTAL_ALIGNMENT_CENTER, VIEW.x, 28, Color(1, 1, 1, 0.7))

	# name + trait + stat bars
	draw_string(font, Vector2(0, 466.0), duck.name, HORIZONTAL_ALIGNMENT_CENTER, VIEW.x, 34, Color.WHITE)
	draw_string(font, Vector2(0, 498.0), duck.trait, HORIZONTAL_ALIGNMENT_CENTER, VIEW.x, 20, Color(1, 1, 1, 0.7))
	_stat_bar("HOP", duck.hop, 536.0)
	_stat_bar("STEER", duck.steer, 572.0)

	if unlocked:
		draw_style_box(_btn_sb(), SEL_PLAY_BTN)
		draw_string(font, Vector2(SEL_PLAY_BTN.position.x, SEL_PLAY_BTN.position.y + 38), "PLAY  >",
			HORIZONTAL_ALIGNMENT_CENTER, SEL_PLAY_BTN.size.x, 28, Color.WHITE)
	else:
		draw_string(font, Vector2(0, SEL_PLAY_BTN.position.y + 38), "locked — earn feathers to unlock",
			HORIZONTAL_ALIGNMENT_CENTER, VIEW.x, 20, Color(1, 1, 1, 0.5))

	# roster thumbnails (locked ones ghosted to a silhouette)
	for i in ROSTER.size():
		var r := _thumb_rect(i)
		var sb := StyleBoxFlat.new()
		sb.bg_color = Color(0.08, 0.12, 0.16, 0.85)
		sb.set_corner_radius_all(10)
		if i == sel_index:
			sb.set_border_width_all(3)
			sb.border_color = Color(1, 0.9, 0.4)
		draw_style_box(sb, r)
		var rd = ROSTER[i]
		if rd.unlocked and rd.species != "" and ducks.has(rd.species):
			var th = ducks[rd.species].get("hero")
			_blit_centered(th if th != null else ducks[rd.species]["idle"][0], r.get_center(), 1.4)
		else:
			var lh = ducks["mallard"].get("hero")
			_blit_modulated(lh if lh != null else ducks["mallard"]["idle"][0], r.get_center(), 1.4, Color(0.34, 0.37, 0.44, 1.0))

func _showcase(cur) -> Array:
	# front-facing turntable: hero face <-> side profiles (never the unflattering belly-up back)
	var hero = cur.get("hero")
	if hero == null:
		hero = cur["idle"][0]
	return [hero, cur["side"][1], hero, cur["side"][-1]]

func _blit_modulated(tex, pos: Vector2, scale: float, mod: Color) -> void:
	if tex == null:
		return
	var sz: Vector2 = tex.get_size() * scale
	draw_texture_rect(tex, Rect2(pos - sz * 0.5, sz), false, mod)

func _stat_bar(label: String, val, y: float) -> void:
	var bx := VIEW.x * 0.5 - 90.0
	draw_string(font, Vector2(bx - 96, y + 15), label, HORIZONTAL_ALIGNMENT_RIGHT, 90, 20, Color(1, 1, 1, 0.8))
	draw_rect(Rect2(bx, y, 200, 16), Color(0, 0, 0, 0.5))
	draw_rect(Rect2(bx, y, 200.0 * clampf(val, 0.0, 1.0), 16), Color(0.4, 0.8, 1.0))

# sprite-stacking: draw slices bottom->top, each rotated by yaw + offset up = fake 3D
func _draw_stack(center: Vector2, scale: float, slices, yaw: float, roll := 0.0, contact_shadow := true) -> void:
	if slices.is_empty():
		_blit_centered(ducks["mallard"]["idle"][0], center, scale * 0.6)
		return
	var n: int = slices.size()
	var gap := scale * 0.9
	if contact_shadow and tex_shadow != null:
		draw_set_transform(center + Vector2(0, 6), yaw, Vector2.ONE)
		var shz := tex_shadow.get_size() * scale * 1.2
		draw_texture_rect(tex_shadow, Rect2(-shz * 0.5, shz), false, Color(0, 0, 0, 0.3))
	for z in n:
		var s: Texture2D = slices[z]
		if s == null:
			continue
		var sz := s.get_size() * scale
		var shade: float = 0.55 + 0.45 * float(z) / float(n)
		var off := Vector2(0, -z * gap).rotated(roll)   # roll tumbles the whole stack
		draw_set_transform(center + off, yaw + roll, Vector2.ONE)
		draw_texture_rect(s, Rect2(-sz * 0.5, sz), false, Color(shade, shade, shade))
	draw_set_transform(Vector2.ZERO, 0.0, Vector2.ONE)

func _draw_diamond(c: Vector2, r: float, col: Color) -> void:
	var pts := PackedVector2Array([
		c + Vector2(0, -r), c + Vector2(r, 0), c + Vector2(0, r), c + Vector2(-r, 0),
	])
	draw_colored_polygon(pts, col)
